# Generated by Django 2.2.6 on 2019-10-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloth',
            name='colour',
            field=models.CharField(default='black', max_length=30),
        ),
    ]
