# Generated by Django 2.2.6 on 2019-11-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_cloth_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='amount',
            new_name='available_in_stock',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='colour',
        ),
    ]
