# Generated by Django 2.2.6 on 2019-11-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.CharField(editable=False, max_length=100)),
                ('items', models.ManyToManyField(related_name='_cart_items_+', to='cart.CartItem')),
            ],
        ),
    ]
