# Generated by Django 2.2.6 on 2019-11-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20191128_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='_cart_items_+', to='cart.CartItem'),
        ),
    ]
