# Generated by Django 2.2.6 on 2019-11-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20191128_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='belongs_to', to='cart.CartItem'),
        ),
    ]
